feat(droppable): x, y position and target within event
mattlewis92/angular-draggable-droppable pull request #113
Opened 2021-12-20 13:10 UTC by soyuka

Hi, this is a suggestion to add some informations to the DragEvent. 

Should I continue working on this and add tests etc. or is it something you don't want?

2021-12-20 13:33 UTC, mattlewis92 commented
> Hi, this is a suggestion to add some informations to the DragEvent.
> 
> Should I continue working on this and add tests etc. or is it something you don't want?

Sure thing, I think it makes sense to add! Out of curiosity, what's your use case?

2022-04-08 08:24 UTC, soyuka commented
Hi, we have a context of containers that can contain other containers. This helps us place "placeholders" according to the position on the parent container (above, below or inside).

2022-04-08 15:08 UTC, mattlewis92 commented on projects/angular-draggable-droppable/src/lib/droppable.directive.ts
> +        let currentDragDropData: DragEvent;
nit: maybe we could rename this from `currentDragDropData` to `currentDragEvent`?

2022-04-08 15:08 UTC, mattlewis92 requested changes
LGTM! Just had one small suggestion then this should be g2g. Thanks for your contribution!

2022-04-15 20:44 UTC, soyuka commented
done and rebased

2022-04-19 11:20 UTC, mattlewis92 approved these changes
LGTM, thank you! 🙌

2022-04-19 11:21 UTC, merged